language: node_js

node_js:
  - 12

# if using Ubuntu 16 need this library
# https://github.com/cypress-io/cypress-documentation/pull/1647
addons:
  apt:
    packages:
    - libgconf-2-4

script:
  - npm run instrumented & wait-on http://localhost:8855
  - npm run cypress:run
  - kill $(jobs -p) || true
